### ISSUE TITLE
[SOLVED] CMakeLists not in the repository

### ISSUE THREAD

**Issue by Richy-Z** [LuauDev/LuauAPI#1]
Unfortunately it looks like you haven't provided the `CMakeLists.txt` file therefore you can't compile the project out of the box. Also visual studio is spewing out errors but I'm more interested in getting the project to compile with CMake.

**Comment by LuauDev** [comment]
okay

**Comment by LuauDev** [comment]
@Richy-Z I apologize for my previous response - I've added the CMakeLists.txt to the repository now. The file is configured with:

- C++17 support
- DLL build settings 
- Required dependencies (OpenSSL, ZLIB, xxhash, zstd)
- All necessary source files and include paths
- Windows-specific settings

Let me know if you have any issues with the build configuration or need any adjustments made to the CMakeLists.txt.
https://github.com/LuauDev/LuauAPI/blob/main/CMakeLists.txt

> Unfortunately it looks like you haven't provided the `CMakeLists.txt` file therefore you can't compile the project out of the box. Also visual studio is spewing out errors but I'm more interested in getting the project to compile with CMake.

**Comment by Richy-Z** [comment]
Thank you, you shall be commended for your impressive work on this project. 🤗
