### ISSUE TITLE
[SOLVED] CMakeLists does not exist 

### ISSUE THREAD

**Issue by am0y** [LuauDev/LuauAPI#2]
CMakeList.txt isnt in the repo please add it

**Comment by LuauDev** [comment]
ok

**Comment by LuauDev** [comment]
@am0y I apologize for my previous response - I've added the CMakeLists.txt to the repository now. The file is configured with:

- C++17 support
- DLL build settings 
- Required dependencies (OpenSSL, ZLIB, xxhash, zstd)
- All necessary source files and include paths
- Windows-specific settings

Let me know if you have any issues with the build configuration or need any adjustments made to the CMakeLists.txt.
https://github.com/LuauDev/LuauAPI/blob/main/CMakeLists.txt
