### ISSUE TITLE
Unable to start program bla bla bla

### ISSUE THREAD

**Issue by bkkpro1980** [LuauDev/LuauAPI#4]
---------------------------
Microsoft Visual Studio
---------------------------
Unable to start program 'D:\VsCode\Projects\vcpkg\build\Release\net8.0-windows\LuauAPI.dll'.

D:\VsCode\Projects\vcpkg\build\Release\net8.0-windows\LuauAPI.dll is not a valid Win32 application.
---------------------------
OK   
---------------------------

this happened after i pressed F5

**Comment by bkkpro1980** [comment]
nvm i fixed it by myself yay

**Comment by LuauDev** [comment]
good lmao

**Comment by LuauDev** [comment]
> nvm i fixed it by myself yay

u just needed to build the dll
please star the github
